version: '2'
services:
  web:
    image: nginx:1.11.1
    ports:
      - "20080:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./images/nginx/config:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./private:/private

  php:
    build:
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/mnt/app

  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "drupal"
      MYSQL_USER: "drupal"
      MYSQL_PASSWORD: "drupal"
    volumes:
      - db:/var/lib/mysql
  
  mail:
    image: mailhog/mailhog
    ports:
      - "2587:587"
      - "28025:8025"
    networks:
      - backend
  
  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    ports:
      - "29000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

volumes:
  db:
    driver: local


networks:
  backend:
    driver: bridge
