version: '2'
services:
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"

  # memcached: 
  #   image: memcached
  #   ports:
  #     - "11211:11211"
      
  web:
    image: nginx:1.11.1
    ports:
      - "20080:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./images/nginx/config:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx

  php:
    build:
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/mnt/app
      - ./images/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
  
  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    ports:
      - "29000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "zaichuan_db"
      MYSQL_USER: "zaichuan"
      MYSQL_PASSWORD: "123456"
    ports:
        - "23306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local


networks:
  backend:
    driver: bridge
