version: '2'
services:
  database:
    image: mariadb
    volumes:
      - "./datadir:/var/lib/mysql"
      - "./bridgedir:/bridgedir"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zhiku_db 
      MYSQL_USER: zhiku
      MYSQL_PASSWORD: 123456
    networks:
      - backend

  mail:
    image: mailhog/mailhog
    ports:
      - "587:587"
      - "8025:8025"
    networks:
      - backend

  web:
    image: bluers/docker-drupal-nginx
    ports:
      - "8000:80"
    volumes:
      - "./web:/var/www/web:rw"
      - "./bridgedir:/bridgedir"
      - "files_public:/var/www_files/public:rw"
      - "files_private:/var/www_files/private:rw"
      - "ssh:/root/.ssh:rw"
    networks:
      - backend

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --api --logLevel=INFO
    ports:
      - '10080:80' # The HTTP port
      - '18080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  database:
    driver: local
  files_public:
    driver: local
  files_private:
    driver: local
  ssh:
    driver: local
